refactor(*): typescript rewrite
typescord/prism-media pull request #2
Opened 2021-02-08 13:38 UTC by Mesteery

En general c'est plutot bon, juste la ou j'ai mis des @expect-error y a des problemes, je les ai pas mit comme solution, mais plus pour que tu les vois, y en a un au pire des cas, on peut le laisser, le deuxieme (vers `copy`), il doit etre absolument etre enleve.

2021-02-08 14:09 UTC, B-Derouet requested changes

2021-02-08 14:09 UTC, B-Derouet commented on src/core/WebmBase.ts
> +  public _transform(chunk: Buffer, encoding: BufferEncoding, done: TransformCallback): void {
private ?

2021-02-08 14:09 UTC, B-Derouet commented on src/core/WebmBase.ts
> +  public _readTag(chunk: Buffer, offset: number): Tag | typeof WebmBaseDemuxer.TOO_SHORT {
private ?

2021-02-08 14:09 UTC, B-Derouet commented on src/core/WebmBase.ts
> +  public _destroy(error: Error | null, callback: (error: Error | null) => void): void {
private ?

2021-02-08 14:09 UTC, B-Derouet commented on src/core/WebmBase.ts
> +  public _final(callback: () => void): void {
private ?

2021-02-08 14:09 UTC, B-Derouet commented on src/core/WebmBase.ts
> +function vintLength(buffer: Buffer, index: number): number | typeof WebmBaseDemuxer.TOO_SHORT {
Il serait plus intéressant de bouger ces fonctions dans des fichiers à part

2021-02-08 14:09 UTC, B-Derouet commented on src/opus/OggDemuxer.ts
> +  public _transform(chunk: Buffer, encoding: BufferEncoding, done: TransformCallback): void {
private ?

2021-02-08 14:09 UTC, B-Derouet commented on src/opus/OggDemuxer.ts
> +  public _destroy(error: Error | null, callback: (error: Error | null) => void): void {
private ?

2021-02-08 14:09 UTC, B-Derouet commented on src/opus/OggDemuxer.ts
> +  public _final(callback: () => void): void {
private ?

2021-02-11 16:13 UTC, Mesteery commented on test/util.ts
> +    stream.on('error', () => reject());
Why ?

2021-02-11 16:24 UTC, B-Derouet commented on test/util.ts
> +    stream.on('error', () => reject());
Oh, I forgot to revert this one...

2021-02-11 17:06 UTC, B-Derouet commented on test/util.ts
> +    stream.on('error', () => reject());
But it's not very important, works the same :+1:

2021-02-11 17:14 UTC, Mesteery commented on test/util.ts
> +    stream.on('error', () => reject());
Yes, and not.
Before, the Error is rejected.
With your changes, the Error is not rejected.

2021-02-13 23:21 UTC, B-Derouet approved these changes
LGTM

2021-02-13 23:31 UTC, merged